package com.aziarets.vividapp.model;

public enum BotUserStatus {
    WITHOUT_STATUS,
    ADDING_GIFT_NAME,
    ADDING_GIFT_URl,
    ADDING_GIFT_DESCRIPTION,
    ADDING_GIFT_PHOTO,
    SEARCHING_FRIEND,
    CONTACTING_DEVELOPER,
    SETTING_PASSWORD
}
